/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  safelist: [
    'row-start-[-11]',
    'col-start-[-11]',
    'row-start-[-10]',
    'col-start-[-10]',
    'row-start-[-9]',
    'col-start-[-9]',
    'row-start-[-8]',
    'col-start-[-8]',
    'row-start-[-7]',
    'col-start-[-7]',
    'row-start-[-6]',
    'col-start-[-6]',
    'row-start-[-5]',
    'col-start-[-5]',
    'row-start-[-4]',
    'col-start-[-4]',
    'row-start-[-3]',
    'col-start-[-3]',
    'row-start-[-2]',
    'col-start-[-2]',
    'row-start-[-1]',
    'col-start-[-1]',
    'row-start-[0]',
    'col-start-[0]',
    'row-start-1',
    'col-start-1',
    'row-start-2',
    'col-start-2',
    'row-start-3',
    'col-start-3',
    'row-start-4',
    'col-start-4',
    'row-start-5',
    'col-start-5',
    'row-start-6',
    'col-start-6',
    'row-start-7',
    'col-start-7',
    'row-start-8',
    'col-start-8',
    'row-start-9',
    'col-start-9',
    'row-start-10',
    'col-start-10',
    'row-start-11',
    'col-start-11'
  ],
  plugins: [],
};