export const fields = {
  start: [
    { id: 0, type: 'start', name: 'Старт!' },
    { id: 1, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 2, type: 'treasury', name: 'Казна' },
    { id: 3, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 4, type: 'tax', name: 'Налог с дохода' },
    { id: 5, type: 'railroad', name: 'Железная дорога' },
    { id: 6, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 7, type: 'chance', name: 'Шанс' },
    { id: 8, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 9, type: 'property', name: 'Недвижимость', ownedBy: 0 },
  ],
  prison: [
    { id: 10, type: 'prison', name: 'Тюрьма' },
    { id: 11, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 12, type: 'power-plant', name: 'Электростанция' },
    { id: 13, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 14, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 15, type: 'railroad', name: 'Железная дорога' },
    { id: 16, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 17, type: 'treasury', name: 'Казна' },
    { id: 18, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 19, type: 'property', name: 'Недвижимость', ownedBy: 0 },
  ],
  parking: [
    { id: 20, type: 'parking', name: 'Бесплатная парковка' },
    { id: 21, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 22, type: 'chance', name: 'Шанс' },
    { id: 23, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 24, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 25, type: 'railroad', name: 'Железная дорога' },
    { id: 26, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 27, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 28, type: 'water-supply', name: 'Водопровод' },
    { id: 29, type: 'property', name: 'Недвижимость', ownedBy: 0 },
  ],
  goToPrison: [
    { id: 30, type: 'goToPrison', name: 'Вы арестованы' },
    { id: 31, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 32, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 33, type: 'treasury', name: 'Казна' },
    { id: 34, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 35, type: 'railroad', name: 'Железная дорога' },
    { id: 36, type: 'chance', name: 'Шанс' },
    { id: 37, type: 'property', name: 'Недвижимость', ownedBy: 0 },
    { id: 38, type: 'tax', name: 'Уплатите сверхналог' },
    { id: 39, type: 'property', name: 'Недвижимость', ownedBy: 0 },
  ],
}
